In [63]:
import pandas as pd

dataset=pd.read_csv('iris.csv').values
print(dataset.shape,dataset)






(150, 5) [[5.1 3.5 1.4 0.2 0. ]
 [4.9 3.  1.4 0.2 0. ]
 [4.7 3.2 1.3 0.2 0. ]
 [4.6 3.1 1.5 0.2 0. ]
 [5.  3.6 1.4 0.2 0. ]
 [5.4 3.9 1.7 0.4 0. ]
 [4.6 3.4 1.4 0.3 0. ]
 [5.  3.4 1.5 0.2 0. ]
 [4.4 2.9 1.4 0.2 0. ]
 [4.9 3.1 1.5 0.1 0. ]
 [5.4 3.7 1.5 0.2 0. ]
 [4.8 3.4 1.6 0.2 0. ]
 [4.8 3.  1.4 0.1 0. ]
 [4.3 3.  1.1 0.1 0. ]
 [5.8 4.  1.2 0.2 0. ]
 [5.7 4.4 1.5 0.4 0. ]
 [5.4 3.9 1.3 0.4 0. ]
 [5.1 3.5 1.4 0.3 0. ]
 [5.7 3.8 1.7 0.3 0. ]
 [5.1 3.8 1.5 0.3 0. ]
 [5.4 3.4 1.7 0.2 0. ]
 [5.1 3.7 1.5 0.4 0. ]
 [4.6 3.6 1.  0.2 0. ]
 [5.1 3.3 1.7 0.5 0. ]
 [4.8 3.4 1.9 0.2 0. ]
 [5.  3.  1.6 0.2 0. ]
 [5.  3.4 1.6 0.4 0. ]
 [5.2 3.5 1.5 0.2 0. ]
 [5.2 3.4 1.4 0.2 0. ]
 [4.7 3.2 1.6 0.2 0. ]
 [4.8 3.1 1.6 0.2 0. ]
 [5.4 3.4 1.5 0.4 0. ]
 [5.2 4.1 1.5 0.1 0. ]
 [5.5 4.2 1.4 0.2 0. ]
 [4.9 3.1 1.5 0.1 0. ]
 [5.  3.2 1.2 0.2 0. ]
 [5.5 3.5 1.3 0.2 0. ]
 [4.9 3.1 1.5 0.1 0. ]
 [4.4 3.  1.3 0.2 0. ]
 [5.1 3.4 1.5 0.2 0. ]
 [5.  3.5 1.3 0.3 0. ]
 [4.5 2.3 1.3 0.3 0. ]
 [4.4 3.2 1.3 0.2 0. ]
 [

In [64]:
data=dataset[:,0:4]
target=dataset[:,4]

print(target)
print(data)



[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2.
 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2.
 2. 2. 2. 2. 2. 2.]
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 

In [65]:
from keras.utils import np_utils

newtarget=np_utils.to_categorical(target)
print(target)
print(newtarget)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2.
 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2.
 2. 2. 2. 2. 2. 2.]
[[1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [

In [66]:
from sklearn.model_selection import train_test_split

data_train,data_test,target_train,target_test=train_test_split(data,newtarget,test_size=0.1)

In [67]:
print(data_train,data_train.shape)

[[4.8 3.4 1.9 0.2]
 [4.9 3.1 1.5 0.1]
 [5.8 2.7 4.1 1. ]
 [6.3 2.3 4.4 1.3]
 [6.  2.7 5.1 1.6]
 [6.3 3.4 5.6 2.4]
 [6.4 3.2 4.5 1.5]
 [6.  3.  4.8 1.8]
 [6.1 2.8 4.7 1.2]
 [5.7 4.4 1.5 0.4]
 [5.9 3.2 4.8 1.8]
 [5.  3.4 1.6 0.4]
 [4.4 2.9 1.4 0.2]
 [7.4 2.8 6.1 1.9]
 [5.  3.4 1.5 0.2]
 [6.1 2.6 5.6 1.4]
 [5.8 2.7 5.1 1.9]
 [5.3 3.7 1.5 0.2]
 [4.5 2.3 1.3 0.3]
 [6.9 3.1 5.1 2.3]
 [6.1 3.  4.9 1.8]
 [6.2 2.9 4.3 1.3]
 [6.5 3.  5.5 1.8]
 [6.7 3.1 4.4 1.4]
 [4.8 3.4 1.6 0.2]
 [5.9 3.  4.2 1.5]
 [5.  3.5 1.6 0.6]
 [6.2 2.2 4.5 1.5]
 [5.1 2.5 3.  1.1]
 [6.3 3.3 4.7 1.6]
 [5.  3.3 1.4 0.2]
 [5.  3.2 1.2 0.2]
 [6.6 3.  4.4 1.4]
 [7.7 2.6 6.9 2.3]
 [5.6 2.9 3.6 1.3]
 [5.4 3.7 1.5 0.2]
 [5.8 2.7 5.1 1.9]
 [6.4 2.8 5.6 2.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.1 3.3 1.7 0.5]
 [5.5 2.3 4.  1.3]
 [5.2 2.7 3.9 1.4]
 [7.2 3.  5.8 1.6]
 [6.7 3.3 5.7 2.1]
 [6.  2.9 4.5 1.5]
 [6.9 3.1 5.4 2.1]
 [5.8 2.7 3.9 1.2]
 [5.5 2.4 3.7 1. ]
 [6.1 2.8 4.  1.3]
 [4.7 3.2 1.6 0.2]
 [7.7 2.8 6.7 2. ]
 [4.9 2.4 3.

In [68]:
print(test_data,test_data.shape)

[[5.4 3.9 1.7 0.4]
 [6.1 3.  4.9 1.8]
 [5.8 2.7 3.9 1.2]
 [7.7 2.6 6.9 2.3]
 [6.3 2.8 5.1 1.5]
 [5.2 3.5 1.5 0.2]
 [6.4 2.9 4.3 1.3]
 [5.1 3.8 1.6 0.2]
 [5.5 2.4 3.8 1.1]
 [5.  3.4 1.6 0.4]
 [7.3 2.9 6.3 1.8]
 [5.  3.5 1.6 0.6]
 [6.1 2.9 4.7 1.4]
 [6.1 2.6 5.6 1.4]
 [6.2 3.4 5.4 2.3]] (15, 4)


In [69]:
from keras.utils import np_utils

newtarget=np_utils.to_categorical(target)



In [70]:
from sklearn.model_selection import train_test_split

data_train,data_test,target_train,target_test=train_test_split(data,newtarget,test_size=0.1)



In [71]:
from keras.models import Sequential
from keras.layers import Dense

model=Sequential()

model.add(Dense(64,input_dim=4,activation='relu'))
model.add(Dense(32,activation='relu'))
model.add(Dense(3,activation='softmax'))

model.compile(loss='categorical_crossentropy',optimizer='adaGrad',metrics=['accuracy'])
model.summary()

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_6 (Dense)              (None, 64)                320       
_________________________________________________________________
dense_7 (Dense)              (None, 32)                2080      
_________________________________________________________________
dense_8 (Dense)              (None, 3)                 99        
Total params: 2,499
Trainable params: 2,499
Non-trainable params: 0
_________________________________________________________________


In [72]:
for layer in model.layers:
    
    print('***********',layer.name,'*************')
    
    parameters=layer.get_weights()
    print(parameters)

*********** dense_6 *************
[array([[-0.1661593 ,  0.00700349,  0.20553535,  0.22824937,  0.15152004,
         0.14260569,  0.10022888, -0.10967207, -0.12258591, -0.02385813,
        -0.04392394, -0.25941113, -0.2858606 , -0.15135314, -0.12327364,
         0.06707758,  0.2352038 , -0.20901436, -0.21798368, -0.26428252,
        -0.09194724, -0.26133716, -0.29505578,  0.04740027,  0.12514043,
         0.15105024, -0.07984771,  0.11968261,  0.15779024,  0.19891283,
         0.15729862, -0.1491006 ,  0.15997776, -0.2958237 , -0.14288975,
         0.27495766,  0.02524865,  0.29517972,  0.14283106,  0.20679659,
         0.17922094, -0.19913009, -0.24897206,  0.02063572,  0.28431916,
        -0.10412949,  0.2770626 , -0.0841022 , -0.19637048, -0.03673556,
        -0.12105781,  0.07325789, -0.06764024,  0.24454272, -0.18239959,
        -0.13122414,  0.10548329,  0.15746441,  0.23234254, -0.25320664,
         0.00831664,  0.20762402,  0.11820713,  0.21119446],
       [ 0.00138363, -0.0969

In [73]:
model.fit(data_train,target_train,epochs=1000,validation_split=0.1)

Epoch 1/1000
4/4 [==============================] - 1s 179ms/step - loss: 1.2745 - accuracy: 0.2946 - val_loss: 1.1402 - val_accuracy: 0.4286
Epoch 2/1000
4/4 [==============================] - 0s 34ms/step - loss: 1.2083 - accuracy: 0.3216 - val_loss: 1.1238 - val_accuracy: 0.4286
Epoch 3/1000
4/4 [==============================] - 0s 38ms/step - loss: 1.1929 - accuracy: 0.3477 - val_loss: 1.1085 - val_accuracy: 0.4286
Epoch 4/1000
4/4 [==============================] - 0s 38ms/step - loss: 1.1681 - accuracy: 0.3310 - val_loss: 1.0940 - val_accuracy: 0.4286
Epoch 5/1000
4/4 [==============================] - 0s 34ms/step - loss: 1.1572 - accuracy: 0.3143 - val_loss: 1.0767 - val_accuracy: 0.4286
Epoch 6/1000
4/4 [==============================] - 0s 34ms/step - loss: 1.1217 - accuracy: 0.3404 - val_loss: 1.0562 - val_accuracy: 0.4286
Epoch 7/1000
4/4 [==============================] - 0s 39ms/step - loss: 1.1111 - accuracy: 0.3091 - val_loss: 1.0385 - val_accuracy: 0.4286
Epoch 8/1000

Epoch 59/1000
4/4 [==============================] - 0s 43ms/step - loss: 0.7904 - accuracy: 0.6560 - val_loss: 0.8037 - val_accuracy: 0.6429
Epoch 60/1000
4/4 [==============================] - 0s 34ms/step - loss: 0.7665 - accuracy: 0.6975 - val_loss: 0.8017 - val_accuracy: 0.6429
Epoch 61/1000
4/4 [==============================] - 0s 31ms/step - loss: 0.7582 - accuracy: 0.7069 - val_loss: 0.7993 - val_accuracy: 0.6429
Epoch 62/1000
4/4 [==============================] - 0s 31ms/step - loss: 0.7710 - accuracy: 0.6695 - val_loss: 0.7968 - val_accuracy: 0.6429
Epoch 63/1000
4/4 [==============================] - 0s 31ms/step - loss: 0.7649 - accuracy: 0.6852 - val_loss: 0.7944 - val_accuracy: 0.6429
Epoch 64/1000
4/4 [==============================] - 0s 31ms/step - loss: 0.7564 - accuracy: 0.6883 - val_loss: 0.7920 - val_accuracy: 0.6429
Epoch 65/1000
4/4 [==============================] - 0s 34ms/step - loss: 0.7482 - accuracy: 0.7048 - val_loss: 0.7900 - val_accuracy: 0.6429
Epoch 

4/4 [==============================] - 0s 30ms/step - loss: 0.6214 - accuracy: 0.7284 - val_loss: 0.6830 - val_accuracy: 0.6429
Epoch 117/1000
4/4 [==============================] - 0s 31ms/step - loss: 0.6077 - accuracy: 0.7492 - val_loss: 0.6816 - val_accuracy: 0.6429
Epoch 118/1000
4/4 [==============================] - 0s 31ms/step - loss: 0.6190 - accuracy: 0.7435 - val_loss: 0.6800 - val_accuracy: 0.6429
Epoch 119/1000
4/4 [==============================] - 0s 32ms/step - loss: 0.6068 - accuracy: 0.7453 - val_loss: 0.6784 - val_accuracy: 0.6429
Epoch 120/1000
4/4 [==============================] - 0s 32ms/step - loss: 0.6033 - accuracy: 0.7296 - val_loss: 0.6768 - val_accuracy: 0.6429
Epoch 121/1000
4/4 [==============================] - 0s 30ms/step - loss: 0.5963 - accuracy: 0.7711 - val_loss: 0.6754 - val_accuracy: 0.6429
Epoch 122/1000
4/4 [==============================] - 0s 32ms/step - loss: 0.6219 - accuracy: 0.7102 - val_loss: 0.6739 - val_accuracy: 0.6429
Epoch 123/1000

4/4 [==============================] - 0s 31ms/step - loss: 0.5431 - accuracy: 0.7866 - val_loss: 0.6203 - val_accuracy: 0.7143
Epoch 174/1000
4/4 [==============================] - 0s 31ms/step - loss: 0.5500 - accuracy: 0.7765 - val_loss: 0.6193 - val_accuracy: 0.7143
Epoch 175/1000
4/4 [==============================] - 0s 29ms/step - loss: 0.5572 - accuracy: 0.7743 - val_loss: 0.6186 - val_accuracy: 0.7143
Epoch 176/1000
4/4 [==============================] - 0s 31ms/step - loss: 0.5649 - accuracy: 0.7462 - val_loss: 0.6178 - val_accuracy: 0.7143
Epoch 177/1000
4/4 [==============================] - 0s 31ms/step - loss: 0.5443 - accuracy: 0.7993 - val_loss: 0.6170 - val_accuracy: 0.7143
Epoch 178/1000
4/4 [==============================] - 0s 30ms/step - loss: 0.5361 - accuracy: 0.7788 - val_loss: 0.6160 - val_accuracy: 0.7143
Epoch 179/1000
4/4 [==============================] - 0s 31ms/step - loss: 0.5638 - accuracy: 0.7726 - val_loss: 0.6150 - val_accuracy: 0.7143
Epoch 180/1000

4/4 [==============================] - 0s 33ms/step - loss: 0.5374 - accuracy: 0.7976 - val_loss: 0.5785 - val_accuracy: 0.7857
Epoch 231/1000
4/4 [==============================] - 0s 30ms/step - loss: 0.5072 - accuracy: 0.8214 - val_loss: 0.5780 - val_accuracy: 0.7857
Epoch 232/1000
4/4 [==============================] - 0s 31ms/step - loss: 0.4779 - accuracy: 0.8351 - val_loss: 0.5773 - val_accuracy: 0.7857
Epoch 233/1000
4/4 [==============================] - 0s 30ms/step - loss: 0.4933 - accuracy: 0.8599 - val_loss: 0.5767 - val_accuracy: 0.7857
Epoch 234/1000
4/4 [==============================] - 0s 30ms/step - loss: 0.5229 - accuracy: 0.8186 - val_loss: 0.5760 - val_accuracy: 0.7857
Epoch 235/1000
4/4 [==============================] - 0s 33ms/step - loss: 0.5141 - accuracy: 0.8214 - val_loss: 0.5754 - val_accuracy: 0.7857
Epoch 236/1000
4/4 [==============================] - 0s 34ms/step - loss: 0.5212 - accuracy: 0.8396 - val_loss: 0.5748 - val_accuracy: 0.7857
Epoch 237/1000

4/4 [==============================] - 0s 32ms/step - loss: 0.4865 - accuracy: 0.8554 - val_loss: 0.5475 - val_accuracy: 0.7857
Epoch 288/1000
4/4 [==============================] - 0s 32ms/step - loss: 0.4726 - accuracy: 0.8763 - val_loss: 0.5471 - val_accuracy: 0.7857
Epoch 289/1000
4/4 [==============================] - 0s 31ms/step - loss: 0.4746 - accuracy: 0.8700 - val_loss: 0.5466 - val_accuracy: 0.7857
Epoch 290/1000
4/4 [==============================] - 0s 32ms/step - loss: 0.4772 - accuracy: 0.8711 - val_loss: 0.5461 - val_accuracy: 0.7857
Epoch 291/1000
4/4 [==============================] - 0s 33ms/step - loss: 0.4472 - accuracy: 0.8619 - val_loss: 0.5455 - val_accuracy: 0.7857
Epoch 292/1000
4/4 [==============================] - 0s 31ms/step - loss: 0.4724 - accuracy: 0.8554 - val_loss: 0.5451 - val_accuracy: 0.7857
Epoch 293/1000
4/4 [==============================] - 0s 31ms/step - loss: 0.4688 - accuracy: 0.8690 - val_loss: 0.5447 - val_accuracy: 0.7857
Epoch 294/1000

4/4 [==============================] - 0s 37ms/step - loss: 0.4575 - accuracy: 0.8937 - val_loss: 0.5221 - val_accuracy: 0.7857
Epoch 345/1000
4/4 [==============================] - 0s 42ms/step - loss: 0.4369 - accuracy: 0.9020 - val_loss: 0.5217 - val_accuracy: 0.7857
Epoch 346/1000
4/4 [==============================] - 0s 34ms/step - loss: 0.4229 - accuracy: 0.8916 - val_loss: 0.5213 - val_accuracy: 0.7857
Epoch 347/1000
4/4 [==============================] - 0s 34ms/step - loss: 0.4556 - accuracy: 0.8978 - val_loss: 0.5210 - val_accuracy: 0.7857
Epoch 348/1000
4/4 [==============================] - 0s 37ms/step - loss: 0.4532 - accuracy: 0.8947 - val_loss: 0.5206 - val_accuracy: 0.7857
Epoch 349/1000
4/4 [==============================] - 0s 36ms/step - loss: 0.4647 - accuracy: 0.8957 - val_loss: 0.5202 - val_accuracy: 0.7857
Epoch 350/1000
4/4 [==============================] - 0s 31ms/step - loss: 0.4317 - accuracy: 0.9020 - val_loss: 0.5198 - val_accuracy: 0.7857
Epoch 351/1000

4/4 [==============================] - 0s 31ms/step - loss: 0.4313 - accuracy: 0.9169 - val_loss: 0.5012 - val_accuracy: 0.8571
Epoch 402/1000
4/4 [==============================] - 0s 31ms/step - loss: 0.4380 - accuracy: 0.9253 - val_loss: 0.5008 - val_accuracy: 0.8571
Epoch 403/1000
4/4 [==============================] - 0s 32ms/step - loss: 0.4346 - accuracy: 0.8951 - val_loss: 0.5004 - val_accuracy: 0.8571
Epoch 404/1000
4/4 [==============================] - 0s 31ms/step - loss: 0.3950 - accuracy: 0.9263 - val_loss: 0.5000 - val_accuracy: 0.8571
Epoch 405/1000
4/4 [==============================] - 0s 30ms/step - loss: 0.4366 - accuracy: 0.9284 - val_loss: 0.4997 - val_accuracy: 0.8571
Epoch 406/1000
4/4 [==============================] - 0s 34ms/step - loss: 0.4096 - accuracy: 0.9074 - val_loss: 0.4993 - val_accuracy: 0.8571
Epoch 407/1000
4/4 [==============================] - 0s 32ms/step - loss: 0.4286 - accuracy: 0.9282 - val_loss: 0.4991 - val_accuracy: 0.8571
Epoch 408/1000

4/4 [==============================] - 0s 31ms/step - loss: 0.4342 - accuracy: 0.9161 - val_loss: 0.4826 - val_accuracy: 0.8571
Epoch 459/1000
4/4 [==============================] - 0s 32ms/step - loss: 0.4130 - accuracy: 0.9234 - val_loss: 0.4824 - val_accuracy: 0.8571
Epoch 460/1000
4/4 [==============================] - 0s 30ms/step - loss: 0.4227 - accuracy: 0.9327 - val_loss: 0.4821 - val_accuracy: 0.8571
Epoch 461/1000
4/4 [==============================] - 0s 34ms/step - loss: 0.3974 - accuracy: 0.9234 - val_loss: 0.4818 - val_accuracy: 0.8571
Epoch 462/1000
4/4 [==============================] - 0s 31ms/step - loss: 0.4229 - accuracy: 0.9234 - val_loss: 0.4815 - val_accuracy: 0.8571
Epoch 463/1000
4/4 [==============================] - 0s 31ms/step - loss: 0.4115 - accuracy: 0.9150 - val_loss: 0.4812 - val_accuracy: 0.8571
Epoch 464/1000
4/4 [==============================] - 0s 39ms/step - loss: 0.3970 - accuracy: 0.9307 - val_loss: 0.4809 - val_accuracy: 0.8571
Epoch 465/1000

4/4 [==============================] - 0s 34ms/step - loss: 0.3750 - accuracy: 0.9581 - val_loss: 0.4665 - val_accuracy: 0.9286
Epoch 516/1000
4/4 [==============================] - 0s 30ms/step - loss: 0.4013 - accuracy: 0.9383 - val_loss: 0.4662 - val_accuracy: 0.9286
Epoch 517/1000
4/4 [==============================] - 0s 30ms/step - loss: 0.3838 - accuracy: 0.9477 - val_loss: 0.4660 - val_accuracy: 0.9286
Epoch 518/1000
4/4 [==============================] - 0s 29ms/step - loss: 0.3878 - accuracy: 0.9592 - val_loss: 0.4657 - val_accuracy: 0.9286
Epoch 519/1000
4/4 [==============================] - 0s 32ms/step - loss: 0.3783 - accuracy: 0.9539 - val_loss: 0.4655 - val_accuracy: 0.9286
Epoch 520/1000
4/4 [==============================] - 0s 31ms/step - loss: 0.3835 - accuracy: 0.9539 - val_loss: 0.4652 - val_accuracy: 0.9286
Epoch 521/1000
4/4 [==============================] - 0s 33ms/step - loss: 0.3885 - accuracy: 0.9394 - val_loss: 0.4649 - val_accuracy: 0.9286
Epoch 522/1000

4/4 [==============================] - 0s 31ms/step - loss: 0.3878 - accuracy: 0.9414 - val_loss: 0.4517 - val_accuracy: 0.9286
Epoch 573/1000
4/4 [==============================] - 0s 33ms/step - loss: 0.4027 - accuracy: 0.9217 - val_loss: 0.4514 - val_accuracy: 0.9286
Epoch 574/1000
4/4 [==============================] - 0s 31ms/step - loss: 0.3928 - accuracy: 0.9467 - val_loss: 0.4512 - val_accuracy: 0.9286
Epoch 575/1000
4/4 [==============================] - 0s 32ms/step - loss: 0.3755 - accuracy: 0.9498 - val_loss: 0.4510 - val_accuracy: 0.9286
Epoch 576/1000
4/4 [==============================] - 0s 33ms/step - loss: 0.3787 - accuracy: 0.9477 - val_loss: 0.4507 - val_accuracy: 0.9286
Epoch 577/1000
4/4 [==============================] - 0s 32ms/step - loss: 0.3674 - accuracy: 0.9508 - val_loss: 0.4505 - val_accuracy: 0.9286
Epoch 578/1000
4/4 [==============================] - 0s 31ms/step - loss: 0.3826 - accuracy: 0.9529 - val_loss: 0.4502 - val_accuracy: 0.9286
Epoch 579/1000

4/4 [==============================] - 0s 31ms/step - loss: 0.3594 - accuracy: 0.9489 - val_loss: 0.4381 - val_accuracy: 0.9286
Epoch 630/1000
4/4 [==============================] - 0s 33ms/step - loss: 0.3813 - accuracy: 0.9404 - val_loss: 0.4379 - val_accuracy: 0.9286
Epoch 631/1000
4/4 [==============================] - 0s 31ms/step - loss: 0.3552 - accuracy: 0.9456 - val_loss: 0.4377 - val_accuracy: 0.9286
Epoch 632/1000
4/4 [==============================] - 0s 31ms/step - loss: 0.3690 - accuracy: 0.9416 - val_loss: 0.4374 - val_accuracy: 0.9286
Epoch 633/1000
4/4 [==============================] - 0s 36ms/step - loss: 0.3633 - accuracy: 0.9560 - val_loss: 0.4372 - val_accuracy: 0.9286
Epoch 634/1000
4/4 [==============================] - 0s 39ms/step - loss: 0.3703 - accuracy: 0.9508 - val_loss: 0.4370 - val_accuracy: 0.9286
Epoch 635/1000
4/4 [==============================] - 0s 52ms/step - loss: 0.3898 - accuracy: 0.9239 - val_loss: 0.4368 - val_accuracy: 0.9286
Epoch 636/1000

4/4 [==============================] - 0s 32ms/step - loss: 0.3423 - accuracy: 0.9500 - val_loss: 0.4257 - val_accuracy: 0.9286
Epoch 687/1000
4/4 [==============================] - 0s 30ms/step - loss: 0.3516 - accuracy: 0.9541 - val_loss: 0.4255 - val_accuracy: 0.9286
Epoch 688/1000
4/4 [==============================] - 0s 33ms/step - loss: 0.3598 - accuracy: 0.9604 - val_loss: 0.4252 - val_accuracy: 0.9286
Epoch 689/1000
4/4 [==============================] - 0s 32ms/step - loss: 0.3561 - accuracy: 0.9625 - val_loss: 0.4251 - val_accuracy: 0.9286
Epoch 690/1000
4/4 [==============================] - 0s 32ms/step - loss: 0.3630 - accuracy: 0.9562 - val_loss: 0.4248 - val_accuracy: 0.9286
Epoch 691/1000
4/4 [==============================] - 0s 30ms/step - loss: 0.3693 - accuracy: 0.9562 - val_loss: 0.4246 - val_accuracy: 0.9286
Epoch 692/1000
4/4 [==============================] - 0s 31ms/step - loss: 0.3562 - accuracy: 0.9333 - val_loss: 0.4244 - val_accuracy: 0.9286
Epoch 693/1000

4/4 [==============================] - 0s 29ms/step - loss: 0.3293 - accuracy: 0.9510 - val_loss: 0.4137 - val_accuracy: 0.9286
Epoch 744/1000
4/4 [==============================] - 0s 33ms/step - loss: 0.3584 - accuracy: 0.9595 - val_loss: 0.4135 - val_accuracy: 0.9286
Epoch 745/1000
4/4 [==============================] - 0s 31ms/step - loss: 0.3590 - accuracy: 0.9658 - val_loss: 0.4133 - val_accuracy: 0.9286
Epoch 746/1000
4/4 [==============================] - 0s 32ms/step - loss: 0.3467 - accuracy: 0.9595 - val_loss: 0.4131 - val_accuracy: 0.9286
Epoch 747/1000
4/4 [==============================] - 0s 30ms/step - loss: 0.3297 - accuracy: 0.9668 - val_loss: 0.4129 - val_accuracy: 0.9286
Epoch 748/1000
4/4 [==============================] - 0s 31ms/step - loss: 0.3513 - accuracy: 0.9481 - val_loss: 0.4127 - val_accuracy: 0.9286
Epoch 749/1000
4/4 [==============================] - 0s 31ms/step - loss: 0.3519 - accuracy: 0.9439 - val_loss: 0.4125 - val_accuracy: 0.9286
Epoch 750/1000

4/4 [==============================] - 0s 32ms/step - loss: 0.3381 - accuracy: 0.9533 - val_loss: 0.4026 - val_accuracy: 0.9286
Epoch 801/1000
4/4 [==============================] - 0s 32ms/step - loss: 0.2993 - accuracy: 0.9647 - val_loss: 0.4024 - val_accuracy: 1.0000
Epoch 802/1000
4/4 [==============================] - 0s 32ms/step - loss: 0.3532 - accuracy: 0.9543 - val_loss: 0.4022 - val_accuracy: 0.9286
Epoch 803/1000
4/4 [==============================] - 0s 32ms/step - loss: 0.3599 - accuracy: 0.9491 - val_loss: 0.4020 - val_accuracy: 0.9286
Epoch 804/1000
4/4 [==============================] - 0s 31ms/step - loss: 0.3330 - accuracy: 0.9720 - val_loss: 0.4018 - val_accuracy: 1.0000
Epoch 805/1000
4/4 [==============================] - 0s 33ms/step - loss: 0.3387 - accuracy: 0.9543 - val_loss: 0.4016 - val_accuracy: 0.9286
Epoch 806/1000
4/4 [==============================] - 0s 32ms/step - loss: 0.3619 - accuracy: 0.9501 - val_loss: 0.4015 - val_accuracy: 1.0000
Epoch 807/1000

4/4 [==============================] - 0s 31ms/step - loss: 0.3320 - accuracy: 0.9678 - val_loss: 0.3920 - val_accuracy: 1.0000
Epoch 858/1000
4/4 [==============================] - 0s 31ms/step - loss: 0.3496 - accuracy: 0.9512 - val_loss: 0.3918 - val_accuracy: 1.0000
Epoch 859/1000
4/4 [==============================] - 0s 33ms/step - loss: 0.3211 - accuracy: 0.9512 - val_loss: 0.3916 - val_accuracy: 1.0000
Epoch 860/1000
4/4 [==============================] - 0s 31ms/step - loss: 0.3113 - accuracy: 0.9647 - val_loss: 0.3914 - val_accuracy: 1.0000
Epoch 861/1000
4/4 [==============================] - 0s 31ms/step - loss: 0.3045 - accuracy: 0.9626 - val_loss: 0.3913 - val_accuracy: 1.0000
Epoch 862/1000
4/4 [==============================] - 0s 30ms/step - loss: 0.3136 - accuracy: 0.9658 - val_loss: 0.3911 - val_accuracy: 1.0000
Epoch 863/1000
4/4 [==============================] - 0s 30ms/step - loss: 0.3301 - accuracy: 0.9647 - val_loss: 0.3909 - val_accuracy: 1.0000
Epoch 864/1000

4/4 [==============================] - 0s 31ms/step - loss: 0.3182 - accuracy: 0.9647 - val_loss: 0.3818 - val_accuracy: 1.0000
Epoch 915/1000
4/4 [==============================] - 0s 35ms/step - loss: 0.3139 - accuracy: 0.9647 - val_loss: 0.3816 - val_accuracy: 1.0000
Epoch 916/1000
4/4 [==============================] - 0s 31ms/step - loss: 0.3057 - accuracy: 0.9616 - val_loss: 0.3815 - val_accuracy: 1.0000
Epoch 917/1000
4/4 [==============================] - 0s 31ms/step - loss: 0.3196 - accuracy: 0.9439 - val_loss: 0.3813 - val_accuracy: 1.0000
Epoch 918/1000
4/4 [==============================] - 0s 31ms/step - loss: 0.3167 - accuracy: 0.9564 - val_loss: 0.3811 - val_accuracy: 1.0000
Epoch 919/1000
4/4 [==============================] - 0s 32ms/step - loss: 0.3365 - accuracy: 0.9533 - val_loss: 0.3810 - val_accuracy: 1.0000
Epoch 920/1000
4/4 [==============================] - 0s 33ms/step - loss: 0.3118 - accuracy: 0.9533 - val_loss: 0.3808 - val_accuracy: 1.0000
Epoch 921/1000

4/4 [==============================] - 0s 36ms/step - loss: 0.2922 - accuracy: 0.9741 - val_loss: 0.3721 - val_accuracy: 1.0000
Epoch 972/1000
4/4 [==============================] - 0s 38ms/step - loss: 0.3073 - accuracy: 0.9597 - val_loss: 0.3719 - val_accuracy: 1.0000
Epoch 973/1000
4/4 [==============================] - 0s 41ms/step - loss: 0.2899 - accuracy: 0.9826 - val_loss: 0.3718 - val_accuracy: 1.0000
Epoch 974/1000
4/4 [==============================] - 0s 39ms/step - loss: 0.3175 - accuracy: 0.9628 - val_loss: 0.3716 - val_accuracy: 1.0000
Epoch 975/1000
4/4 [==============================] - 0s 40ms/step - loss: 0.3197 - accuracy: 0.9574 - val_loss: 0.3714 - val_accuracy: 1.0000
Epoch 976/1000
4/4 [==============================] - 0s 38ms/step - loss: 0.3043 - accuracy: 0.9826 - val_loss: 0.3713 - val_accuracy: 1.0000
Epoch 977/1000
4/4 [==============================] - 0s 33ms/step - loss: 0.2973 - accuracy: 0.9720 - val_loss: 0.3711 - val_accuracy: 1.0000
Epoch 978/1000

In [77]:
from matplotlib import pyplot as plt

plt.plot(model.history.history['loss'],label='loss')
plt.plot(model.history.history['val_loss'],label='val loss')
plt.legend()
plt.xlabel('#epoch')
plt.ylabel('loss')
plt.show()

KeyError: 'loss'

In [76]:
plt.plot(model.history.history['accuracy'],label='accuracy')
plt.plot(model.history.history['val_accuracy'],label='val accuracy')
plt.legend()
plt.xlabel('#epoch')
plt.xlabel('loss')
plt.show()

KeyError: 'accuracy'

In [75]:
import numpy as np

test_data_1=np.array([5.3,2.3,4.7,2.1]).reshape(1,-1)

predicted_target_1=model.predict(test_data_1)
print(predicted_target_1)

[[0.00332215 0.23411173 0.76256615]]


In [54]:
label=np.argmax(predicted_target_1)
print(label)

2


In [55]:
predicted_target=model.predict(test_data)
print(predicted_target)
print(np.argmax(predicted_target,axis=1))

[[9.6140891e-01 3.8034838e-02 5.5627403e-04]
 [1.1508082e-02 3.7487835e-01 6.1361355e-01]
 [6.6322990e-02 7.0753139e-01 2.2614570e-01]
 [2.0231075e-04 7.6350033e-02 9.2344767e-01]
 [9.2874421e-03 4.2350459e-01 5.6720799e-01]
 [9.5941162e-01 3.9912742e-02 6.7563186e-04]
 [4.8118670e-02 7.2263080e-01 2.2925061e-01]
 [9.6677744e-01 3.2721668e-02 5.0086412e-04]
 [5.5110045e-02 6.7105693e-01 2.7383307e-01]
 [9.3563366e-01 6.2940799e-02 1.4255738e-03]
 [1.0607395e-03 2.0479417e-01 7.9414511e-01]
 [9.3094999e-01 6.7360371e-02 1.6895984e-03]
 [2.2865446e-02 5.6353909e-01 4.1359541e-01]
 [2.7883130e-03 2.6279816e-01 7.3441356e-01]
 [4.0936568e-03 1.9471984e-01 8.0118650e-01]]
[0 2 1 2 2 0 1 0 1 0 2 0 1 2 2]


In [78]:
print(target_test)
print(np.argmax(target_test,axis=1))

[[1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]]
[0 0 1 0 1 2 1 2 1 1 1 2 2 1 2]


In [79]:
from sklearn.metrics import accuracy_score

acc=accuracy_score(np.argmax(target_test,axis=1),np.argmax(predicted_target,axis=1))
print('accuracy:',acc)

accuracy: 0.3333333333333333
